### Create Appointment
POST http://localhost:5000/api/appointments/create
Content-Type: application/json

{
    "name": "Test Appointment 2",
    "email": "test2@example.com",
    "phone": "09079573532",
    "packageType": "newborn",
    "preferredDate": "2026-04-02",
    "preferredTime": "3:00",
    "durationHours": 2,
    "location": "QC",
    "specialRequests": "Test2"
}

### Get All Appointments
GET http://localhost:5000/api/appointments/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YWNlZDBjYTcyOWY1MTIzODVhMDEwMCIsImlhdCI6MTc3NDkzNzU3OSwiZXhwIjoxNzc1MDIzOTc5fQ.x4UUjOyVvHsi9X6OVNJCeyqkPDlL7b3Nf1P6yUx0Rms

### View Appointment
GET http://localhost:5000/api/appointments/view/69cb65538a8d306b8c9d3b89
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YWNlZDBjYTcyOWY1MTIzODVhMDEwMCIsImlhdCI6MTc3NDkzNzU3OSwiZXhwIjoxNzc1MDIzOTc5fQ.x4UUjOyVvHsi9X6OVNJCeyqkPDlL7b3Nf1P6yUx0Rms


### Update Appointment
PUT http://localhost:5000/api/appointments/update/69cb65538a8d306b8c9d3b89
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YWNlZDBjYTcyOWY1MTIzODVhMDEwMCIsImlhdCI6MTc3NDkzNzU3OSwiZXhwIjoxNzc1MDIzOTc5fQ.x4UUjOyVvHsi9X6OVNJCeyqkPDlL7b3Nf1P6yUx0Rms

{
    "status": "completed",
    "notes": "Appointment completed"
}

### Delete Appointment
DELETE http://localhost:5000/api/appointments/delete/69cb664a8a8d306b8c9d3b8f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YWNlZDBjYTcyOWY1MTIzODVhMDEwMCIsImlhdCI6MTc3NDkzNzU3OSwiZXhwIjoxNzc1MDIzOTc5fQ.x4UUjOyVvHsi9X6OVNJCeyqkPDlL7b3Nf1P6yUx0Rms


### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

### Confirm Appointment
GET http://localhost:5000/api/appointments/confirmed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YWNlZDBjYTcyOWY1MTIzODVhMDEwMCIsImlhdCI6MTc3NTE5MzMxOSwiZXhwIjoxNzc1Mjc5NzE5fQ.goesU4Dv2FOlPRLL8mWkrZWpkdBpMdv0SBI-x2-z_Bw